# -*- coding: utf-8 -*-
"""Day 72.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_GJEHWewPth6u2Q6qh6BFAqLpOmpOCC
"""

import pandas as pd

df = pd.read_csv("salaries_by_college_major.csv")

df.head()

df.shape

df.columns

df.isna()

df.tail()

clean_df = df.dropna()
clean_df.tail()

clean_df['Starting Median Salary']

clean_df['Starting Median Salary'].max()

clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]

clean_df.loc[43]

print(clean_df["Mid-Career Median Salary"].max())
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")
clean_df['Undergraduate Major'][clean_df['Mid-Career Median Salary'].idxmax()]

print(clean_df['Starting Median Salary'].min())
print(clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()])

clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

substract_column=clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, "Difference", substract_column)

clean_df.tail()

low_risk = clean_df.sort_values('Difference')
low_risk[['Undergraduate Major', 'Difference']].head()

"""Using the .sort_values() method, can you find the degrees with the highest potential? Find the top 5 degrees with the highest values in the 90th percentile."""

highest_salaries = clean_df.sort_values("Mid-Career 90th Percentile Salary", ascending=False).head()
print(highest_salaries[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']])

"""Also, find the degrees with the greatest spread in salaries. Which majors have the largest difference between high and low earners after graduation."""

highest_difference=clean_df.sort_values("Difference", ascending=False)
print(highest_difference[['Undergraduate Major', 'Difference']].head())

clean_df.groupby('Group').count()

clean_df.groupby('Group')[["Difference", "Starting Median Salary", "Mid-Career Median Salary", "Mid-Career 10th Percentile Salary", "Mid-Career 90th Percentile Salary"]].mean().head()

pd.options.display.float_format = '{:,.2f}'.format