question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
             "you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]
second_bank = {"response_code": 0,
               "results": [{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                            "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                            "question": "Dihydrogen Monoxide is a dangerous chemical.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "medium",
                            "category": "Entertainment: Video Games",
                            "question": "A cancelled Call Of Duty title would have taken place in ancient Rome.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "medium", "category": "Science: Gadgets",
                            "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                            "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                            "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "medium",
                            "category": "Entertainment: Video Games",
                            "question": "The first PlayStation console was released in the USA on December 3rd, 1994.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Animals",
                            "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Politics",
                            "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                            "question": "Ferrari has never made a V10 engine for any of its cars.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                            "question": "In the Super Mario series, the character Pauline is a Princess like Princess Peach.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
                            "question": "&quot;PAYDAY: The Heist&quot; is a sequel to the board game &quot;Payday&quot;.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                            "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "medium", "category": "History",
                            "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Science: Mathematics",
                            "question": "An isosceles triangle has two sides of equal length as opposed to three.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                            "question": "In &quot;Super Mario 3D World&quot;, the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                            "question": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy",
                            "category": "Entertainment: Japanese Anime &amp; Manga",
                            "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of Hawaii.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "medium",
                            "category": "Entertainment: Television",
                            "question": "Klingons once had a period of Democracy in their history, they referred to it as the &quot;Dark Times&quot;.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                            "question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                            "question": "Eurobeat is primarily an Italian genre of music.",
                            "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                            "question": "Ping-Pong originated in England", "correct_answer": "True",
                            "incorrect_answers": ["False"]},
                           {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                            "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                            "question": "The Chevrolet Corvette has always been made exclusively with V8 engines only.",
                            "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"type": "boolean", "difficulty": "medium",
                            "category": "Entertainment: Video Games",
                            "question": "In &quot;Mother 3,&quot; the bird on the Ultimate Chimera&#039;s head is there only for decoration.",
                            "correct_answer": "False", "incorrect_answers": ["True"]}]}
